name: My First GitHub Action

on:
  push:
  pull_request:

jobs:
  print-message:
    runs-on: ubuntu-latest

    steps:
      - name: Print a message
        run: echo "Hello! This workflow is running 🎉"

